name: golangci-lint

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
      branches: [ main, feat/* ]

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go Setup
        uses: ./.github/actions/go-setup-action
        with:
          go-version: ${{ vars.GO_VERSION }}
          go-private: ${{ vars.GO_PRIVATE_REPO }}
          git-user: ${{ secrets.GIT_USER }}
          git-pass: ${{ secrets.GIT_PASS }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: ${{ vars.GOLANGCI_VERSION || 'v1.61.0' }}

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go
          # skip-go-installation: true
